// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  pourquoi: dynamic(() => import("./Pourquoi")),
  test: dynamic(() => import("./TestHead")),
  test_body: dynamic(() => import("./TestBody")),
};
